// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// http: POST /subscriptions
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	// http: DELETE /subscriptions/:id
	DeleteSubscription(ctx context.Context, id int32) error
	// subscriptions.sql
	// http: GET /subscriptions/:id
	GetSubscription(ctx context.Context, id int32) (Subscription, error)
	// http: GET /subscriptions/total-value
	GetTotalValueSubscription(ctx context.Context, arg GetTotalValueSubscriptionParams) (int64, error)
	// http: GET /subscriptions
	ListSubscriptions(ctx context.Context) ([]Subscription, error)
	// http: PATCH /subscriptions/:id
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error
}

var _ Querier = (*Queries)(nil)
