// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    user_id, service_name, price, start_date, end_date
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, service_name, price, start_date, end_date
`

type CreateSubscriptionParams struct {
	UserID      string           `json:"user_id"`
	ServiceName string           `json:"service_name"`
	Price       int32            `json:"price"`
	StartDate   pgtype.Timestamp `json:"start_date"`
	EndDate     pgtype.Timestamp `json:"end_date"`
}

// http: POST /subscriptions
func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = $1
`

// http: DELETE /subscriptions/:id
func (q *Queries) DeleteSubscription(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getSubscription = `-- name: GetSubscription :one

SELECT id, user_id, service_name, price, start_date, end_date FROM subscriptions WHERE id = $1
`

// subscriptions.sql
// http: GET /subscriptions/:id
func (q *Queries) GetSubscription(ctx context.Context, id int32) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getTotalValueSubscription = `-- name: GetTotalValueSubscription :one
SELECT SUM(price) FROM subscriptions
WHERE (user_id = $1 OR NOT $5::bool) AND (service_name = $2 OR NOT $6::bool) AND start_date BETWEEN $3 AND $4
GROUP BY service_name, user_id
`

type GetTotalValueSubscriptionParams struct {
	UserID              string           `json:"user_id"`
	ServiceName         string           `json:"service_name"`
	StartDate           pgtype.Timestamp `json:"start_date"`
	StartDate_2         pgtype.Timestamp `json:"start_date_2"`
	FilterByUserID      bool             `json:"filter_by_user_id"`
	FilterByServiceName bool             `json:"filter_by_service_name"`
}

// http: GET /subscriptions/total-value
func (q *Queries) GetTotalValueSubscription(ctx context.Context, arg GetTotalValueSubscriptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalValueSubscription,
		arg.UserID,
		arg.ServiceName,
		arg.StartDate,
		arg.StartDate_2,
		arg.FilterByUserID,
		arg.FilterByServiceName,
	)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, user_id, service_name, price, start_date, end_date FROM subscriptions
`

// http: GET /subscriptions
func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.Price,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions
SET user_id = $2, service_name = $3, price = $4, start_date = $5, end_date = $6
WHERE id = $1
`

type UpdateSubscriptionParams struct {
	ID          int32            `json:"id"`
	UserID      string           `json:"user_id"`
	ServiceName string           `json:"service_name"`
	Price       int32            `json:"price"`
	StartDate   pgtype.Timestamp `json:"start_date"`
	EndDate     pgtype.Timestamp `json:"end_date"`
}

// http: PATCH /subscriptions/:id
func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription,
		arg.ID,
		arg.UserID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}
