// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    user_id, service_name, price, start_date, end_date
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, service_name, price, start_date, end_date
`

type CreateSubscriptionParams struct {
	UserID      string           `json:"user_id"`
	ServiceName string           `json:"service_name"`
	Price       int32            `json:"price"`
	StartDate   pgtype.Timestamp `json:"start_date"`
	EndDate     pgtype.Timestamp `json:"end_date"`
}

// http: POST /subscriptions
func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions WHERE id = $1
`

// http: DELETE /subscriptions/:id
func (q *Queries) DeleteSubscription(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getEarliestStartDateForUser = `-- name: GetEarliestStartDateForUser :one
SELECT MIN(start_date) FROM subscriptions WHERE user_id = $1
`

func (q *Queries) GetEarliestStartDateForUser(ctx context.Context, userID string) (interface{}, error) {
	row := q.db.QueryRow(ctx, getEarliestStartDateForUser, userID)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const getSubscription = `-- name: GetSubscription :one

SELECT id, user_id, service_name, price, start_date, end_date FROM subscriptions WHERE id = $1
`

// subscriptions.sql
// http: GET /subscriptions/:id
func (q *Queries) GetSubscription(ctx context.Context, id int32) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getTotalValueSubscription = `-- name: GetTotalValueSubscription :one
SELECT COALESCE(SUM(price), 0) FROM subscriptions
WHERE (user_id = $1 OR NOT $5::bool) AND (service_name = $2 OR NOT $6::bool) AND start_date BETWEEN $3 AND $4
`

type GetTotalValueSubscriptionParams struct {
	UserID      string           `json:"user_id"`
	ServiceName string           `json:"service_name"`
	StartDate   pgtype.Timestamp `json:"start_date"`
	StartDate_2 pgtype.Timestamp `json:"start_date_2"`
	Column5     bool             `json:"column_5"`
	Column6     bool             `json:"column_6"`
}

// http: GET /subscriptions/total-value
func (q *Queries) GetTotalValueSubscription(ctx context.Context, arg GetTotalValueSubscriptionParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalValueSubscription,
		arg.UserID,
		arg.ServiceName,
		arg.StartDate,
		arg.StartDate_2,
		arg.Column5,
		arg.Column6,
	)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, user_id, service_name, price, start_date, end_date FROM subscriptions
`

// http: GET /subscriptions
func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.Price,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions
SET 
    user_id = CASE WHEN $2::text IS NOT NULL THEN $2 ELSE user_id END,
    service_name = CASE WHEN $3::text IS NOT NULL THEN $3 ELSE service_name END,
    price = CASE WHEN $4::integer IS NOT NULL THEN $4 ELSE price END,
    start_date = CASE WHEN $5::timestamp IS NOT NULL THEN $5 ELSE start_date END,
    end_date = CASE WHEN $6::timestamp IS NOT NULL THEN $6 ELSE end_date END
WHERE id = $1
`

type UpdateSubscriptionParams struct {
	ID      int32            `json:"id"`
	Column2 string           `json:"column_2"`
	Column3 string           `json:"column_3"`
	Column4 int32            `json:"column_4"`
	Column5 pgtype.Timestamp `json:"column_5"`
	Column6 pgtype.Timestamp `json:"column_6"`
}

// http: PATCH /subscriptions/:id
func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	return err
}
